MOCK_SPOTS = [
    {
        "spot_id": "spot_green_park",
        "color": "green",
        "object_label": "tree",
        "lat": 37.56652,
        "lng": 126.97802,
        "shared_user_percent": 36,
    },
    {
        "spot_id": "spot_blue_river",
        "color": "blue",
        "object_label": "sky",
        "lat": 37.515,
        "lng": 127.102,
        "shared_user_percent": 21,
    },
    {
        "spot_id": "spot_yellow_cafe",
        "color": "yellow",
        "object_label": "sign",
        "lat": 37.551,
        "lng": 126.925,
        "shared_user_percent": 18,
    },
    {
        "spot_id": "spot_white_cloud",
        "color": "white",
        "object_label": "cloud",
        "lat": 37.570,
        "lng": 126.982,
        "shared_user_percent": 12,
    },
    {
        "spot_id": "spot_black_shadow",
        "color": "black",
        "object_label": "shadow",
        "lat": 37.560,
        "lng": 126.970,
        "shared_user_percent": 9,
    },
]
